apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: SSP-d-eks
  region: ap-southeast-2
  version: "1.18"
  tags:
    ServiceName: SSP

kubernetesNetworkConfig:
  serviceIPv4CIDR: 10.244.0.0/17

vpc:
  subnets:
    public:
      ap-southeast-2a:
        id: subnet-00000000000000000
      ap-southeast-2c:
        id: subnet-11111111111111111
    private:
      ap-southeast-2a:
        id: subnet-22222222222222222
      ap-southeast-2c:
        id: subnet-33333333333333333

privateCluster:
  enabled: true
