apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: SSP-d-eks
  region: ap-southeast-2
  version: "1.18"
  tags:
    ServiceName: SSP

kubernetesNetworkConfig:
  serviceIPv4CIDR: 10.244.0.0/17

vpc:
#  cidr: 100.64.15.0/24
  subnets:
    public:
      ap-southeast-2a:
        id: subnet-0a8a8b25014c83a11
      ap-southeast-2c:
        id: subnet-0d91e66fd2aaa8c3a
    private:
      ap-southeast-2a:
        id: subnet-041c67f72d6f47c6d
      ap-southeast-2c:
        id: subnet-0c89fc2dd49642638
  clusterEndpoints:      # can't use when privateCluster enabled
    publicAccess: true   # default : fasle
    privateAccess: true  # default : false

# allows configuring a fully-private cluster in which no node has outbound internet access, and private access to AWS services is enabled via VPC endpoints
# 이거 true 로 하면 VPC에 IGW가 생성되지 않아서 접속 불가능해짐...왜 이걸 넣지? 그냥 public 으로 만들고 설정한뒤에 private 로 바꾸던가;;
#privateCluster:
#  enabled: true          # default : false

#availabilityZones: ["ap-southeast-2a", "ap-southeast-2c"]
