apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: SSP-d-eks
  region: ap-southeast-2

managedNodeGroups:
  - name: SSP-d-eks-ng-fe
    instanceType: m5.large
    availabilityZones:
      - ap-southeast-2a
      - ap-southeast-2c
#    subnets:
#      - subnet-0d06d287dc930f2c8
#      - subnet-000af519e80a27590
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: SSP-d-key
    labels:
      role: worker
    privateNetworking: true
    tags:
      nodegroup-role: worker
      ServiceName: SSP
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
#    ami: ami-0e124de4755b2734d
    maxPodsPerNode: 110
    instanceName: node-fe        # EC2 Name Taga                          :      -ng-fe
    instancePrefix: SSP-d        # EC2 Name Prefix(Name Tag 앞에 붙일 값) : SSP-d
