apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: SSP-d-eks
  region: ap-northeast-2
managedNodeGroups:
  - name: worker-4-16
    instanceType: m5.xlarge
    availabilityZones:
      - ap-northeast-2a
      - ap-northeast-2c
    subnets:
      - subnet-00000000000000000
      - subnet-11111111111111111
    desiredCapacity: 3
    minSize: 2
    maxSize: 4
    volumeSize: 80
    ssh:
      allow: true
      publicKeyName: SSP-d-eks-key
    labels:
      role: worker
    privateNetworking: true
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        efs: true
        albIngress: true
        cloudWatch: true
    ami: ami-11111111111111111
    maxPodsPerNode: 110
